name: Metrics

on:
  schedule: [{cron: "0 8,12,20 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  header-iso-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: silv-io 
          template: classic
          config_timezone: Europe/Vienna

          base: header
          filename: header-iso-calendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: silv-io
          template: classic
          config_timezone: Europe/Vienna

          base: ""
          filename: habits.svg
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
